version: "3.6"
services:
  grafana:
    image: jberny/katacoda-promql-grafana:latest
    ports:
      - "3000:3000"
    networks:
      - promql-net
  prometheus:
    image: docker.io/jberny/katacoda-promql-prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - promql-net
  # alertmanager:
  #   image: prom/alertmanager:v0.20.0
  #   ports:
  #     - "9093:9093"
  #   networks:
  #     - promql-net
  # mattermost:
  #   image: mattermost/mattermost-preview:5.14.0
  #   ports:
  #     - "8065:8065"
  mondemoapi:
    image: jberny/mondemoapi:v0.0.3
    ports:
      - "8080:8080"
    networks:
      - promql-net

networks:
  promql-net:

