global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 1m

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 127.0.0.1:9093

scrape_configs:
  - job_name: mondemoapi
    scrape_timeout: 10s
    scrape_interval: 10s
    static_configs:
      - targets:
        - mondemoapi:8080